[build]
	base = "/"
	publish = "/dist"
	command = "astro build"
	
[[headers]]
	for = "/*"
	[headers.values]
		X-Frame-Options = "SAMEORIGIN"
		X-XSS-Protection = "1; mode=block"
		X-Content-Type-Options = "nosniff"
		Referrer-Policy = "strict-origin-when-cross-origin"
		Permissions-Policy = "interest-cohort=()"
		Content-Security-Policy = "upgrade-insecure-requests"
